# Site settings
name: Michelle Li
title: Michelle Li | Data Scientist
description: Data scientist skilled in implementing machine learning to solve business problems
url: https://michelleli.tech/
baseurl: ""
email: michelle.li.524@gmail.com
cover: img/og.png
logo: img/emojis/chart.png
resume: resume.pdf
social:
  - title: resume
    url: resume.pdf
  - title: email
    url: mailto:michelle.li.524@gmail.com
  - title: github
    url: https://github.com/michellekli
  - title: linkedin
    url: https://www.linkedin.com/in/michelleli524

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
